services:
  mariadb:
    image: mariadb:oumimoun
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: always
    networks:
      - inception_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 10
      start_period: 30s
      start_interval: 30s
      timeout: 5s

  nginx:
    image: nginx:oumimoun
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8443:8443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always

  wordpress:
    image: wordpress:oumimoun
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USERNAME=${WP_ADMIN_USERNAME}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER_USERNAME=${WP_USER_USERNAME}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_ROLE=${WP_USER_ROLE}
    restart: always

volumes:
  mariadb_data:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/oumimoun/data
  wordpress_data:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/oumimoun/data

networks:
  inception_network:
    driver: bridge
